1. 去中心化 X：N*M N为维数 ，M为观测值个数
2. 计算协方差矩阵 np.cov()
3. 计算协方差矩阵的特征值和特征向量:np.eig()
4. 对特征值进行排序 argsort() 返回从小到大排序下标，


In [32]:
import scipy as sp
import numpy as np
# 两个维度，五个观测值
x = np.mat([[-1,-1,0,2,0],[-2,0,0,1,1]])
covX = np.cov(x)
print covX


[[ 1.5  1. ]
 [ 1.   1.5]]


In [21]:
eigVals,eigVects = np.linalg.eig(np.mat(covX))
print eigVals
print eigVects

[ 2.5  0.5]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


 eigVects:标准化的特征向量，每一列为一个特征向量
 
[ 2.5  0.5]

[[ 0.70710678 -0.70710678]

 [ 0.70710678  0.70710678]]

In [47]:
eigindex = sorted(np.argsort(eigVals))
#  sorted 从大到小排列，reverse = True 从小到大排列
print eigindex
#  根据eigindex 得到从0 到 K 的特征向量，组成矩阵
redEigVects  = eigVects[:,eigindex[0:1]]
print redEigVects

#  将维处理
Y = redEigVects.T * x
print Y

#  还原
x_new = redEigVects.T.I * Y
print x
print x_new


[0, 1]
[[ 0.70710678]
 [ 0.70710678]]
[[-2.12132034 -0.70710678  0.          2.12132034  0.70710678]]
[[-1 -1  0  2  0]
 [-2  0  0  1  1]]
[[-1.5 -0.5  0.   1.5  0.5]
 [-1.5 -0.5  0.   1.5  0.5]]
